Models/ErrorViewModel.cs
namespace KendoUI.Models
{
	public class ErrorViewModel
	{
		public string? RequestId { get; set; }

		public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
	}
}

Models/FormModel.cs
using KendoUI.Models.SubForms;
using Microsoft.VisualBasic;

namespace KendoUI.Models.FromModel{
public class Form{
    public long FormID{get;set;} 
    public string Mantralaya {get; set;}
    public long OfficeCodeNo { get; set; }
    public string FiscalYear {get; set;}
    public long KharchaNikasasNo {get; set;}
    public long KharchaNikasasGariakoNo {get; set;}
    public string Date { get; set; }
        public ICollection<SubForm> SubForms { get; set; }
    }
}

Models/SubFrom.cs
using KendoUI.Models.FromModel;

namespace KendoUI.Models.SubForms{
    public class SubForm{
        public long SN{get; set;}
        public string Name{get; set;}
        public string Symbol_No { get; set;}
        public string Specificatin_No { get; set;}
        public string Akin_no { get; set; }
        public string Quantity { get; set;}
        public string Rate { get; set;}
        public string Remark { get; set;}
        public long FormID{get; set;}
        public Form Form{get; set;}
    }
}

Controllers/FormController.cs
using KendoUI.Models.FromModel;
using Microsoft.AspNetCore.Mvc;

namespace KendoUI.FromController{
    public class FormController:Controller
    {
        [HttpGet]
        public IActionResult Index(){
            return View();
        }
        [HttpPost]
        public IActionResult Index(Form jsonOBJ) { 
            return View (jsonOBJ);
        }
        public IActionResult FormFroHaideep(){
            return View();
        }
        
    }
}

Controllers/HomeController.cs
using KendoUI.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using System.Text.Json.Nodes;

namespace KendoUI.Controllers
{
	public class HomeController : Controller
	{
		private readonly ILogger<HomeController> _logger;

		public HomeController(ILogger<HomeController> logger)
		{
			_logger = logger;
		}

		public IActionResult Index()
		{
			return View();
		}

		public IActionResult TestIndex()
		{
			return View();
		}

		public IActionResult Form()
		{
			return View();
		}

		public IActionResult Haideep()
		{
			return View();
		}


		public IActionResult KendoDropDown()
		{
			return View();
		}

		[ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
		public IActionResult Error()
		{
			return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
		}

		public JsonResult KarlayaCode()
		{
			Dictionary<string, string> officeList = new Dictionary<string, string>();
			officeList.Add("name", "Haideep");
            return Json(officeList);

        }
        [HttpPost]
		public IActionResult Post()
		{
			return Ok();
		}
		[HttpPost]
		public IActionResult Update()
		{
			return Ok();
		}
	}
}

Views/Form/FormFroHaideep.cshtml
@{
    ViewData["Title"] = "FormFroHaideep";
}
<!DOCTYPE html>
<html>

<head>
    <title></title>
    <link href="~/css/default-main.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>


    <script src="~/js/kendo.all.min.js"></script>
    <script src="~/js/kendo-ui-license.js"></script>

</head>

<body>
    @* //<script src="~/js/products.js"></script> *@

    <div id="example">
        <div id="grid"></div>

        <script>
            $(document).ready(function () {
                var products = [{
                    ProductID: 1,
                    ProductName: "Chai",
                    SupplierID: 1,
                    CategoryID: 1,
                    QuantityPerUnit: "10 boxes x 20 bags",
                    UnitPrice: 18.0000,
                    UnitsInStock: 39,
                    UnitsOnOrder: 0,
                    ReorderLevel: 10,
                    Discontinued: false

                }, {
                    ProductID: 2,
                    ProductName: "Chang",
                    SupplierID: 1,
                    CategoryID: 1,
                    QuantityPerUnit: "24 - 12 oz bottles",
                    UnitPrice: 19.0000,
                    UnitsInStock: 17,
                    UnitsOnOrder: 40,
                    ReorderLevel: 25,
                    Discontinued: false

                }];
                $("#grid").kendoGrid({
                    dataSource: {
                        data: products,
                        schema: {
                            model: {
                                fields: {
                                    ProductName: { type: "string" },
                                    UnitPrice: { type: "number" },
                                    UnitsInStock: { type: "number" },
                                    Discontinued: { type: "boolean" }
                                }
                            }
                        },
                        pageSize: 20
                    },
                    height: 550,
                    scrollable: true,
                    sortable: true,
                    filterable: true,
                    pageable: {
                        input: true,
                        numeric: false
                    },
                    columns: [
                        "ProductName",
                        { field: "UnitPrice", title: "Unit Price", format: "{0:c}", width: "130px" },
                        { field: "UnitsInStock", title: "Units In Stock", width: "130px" },
                        { field: "Discontinued", width: "130px" }
                    ],
                    editable: true
                });
            });
        </script>
    </div>



</body>

</html>

Views/Home/Haideep.cshtml
<!DOCTYPE html>
<html>
<head>
    <link href="~/css/default-main.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <script src="~/js/kendo.all.min.js"></script>
    <script src="~/js/kendo-ui-license.js"></script>
</head>
<body>
    <script src="https://unpkg.com/jszip/dist/jszip.min.js"></script>

<div id="example">
    <div id="grid"></div>
    <script>
        $(document).ready(function () {
                dataSource = new kendo.data.DataSource({
                    transport: {
                        read: {
                            url: "http://localhost:5268/Home/KarlayaCode/",
                            dataType: "json"
                        }
                        
                    },
                    batch: true,
                    pageSize: 20,
                    autoSync: true,
                    aggregate: [{
                        field: "TotalSales",
                        aggregate: "sum"
                    }],
                    group: {
                        field: "Category.CategoryName",
                        dir: "desc",
                        aggregates: [
                            { field: "TotalSales", aggregate: "sum" }
                        ]
                    },
                    schema: {
                        model: {
                            id: "ProductID",
                            fields: {
                                TargetSales: { type: "number", editable: false },
                                LastSupply: { type: "date" },
                                UnitPrice: { type: "number" },
                                UnitsInStock: { type: "number" },
                                
                                
                            }
                        }
                    }
                });

            $("#grid").kendoGrid({
                dataSource: dataSource,
                columnMenu: {
                    filterable: false
                },
                height: 680,
                editable: "incell",
                pageable: true,
                sortable: true,
                navigatable: true,
                resizable: true,
                reorderable: true,
                groupable: true,
                filterable: true,
                dataBound: onDataBound,
                toolbar: ["excel", "pdf", "search"],
                columns: [ {
                    field: "ProductName",
                    title: "Product Name",
                    template: "<div class='product-photo' style='background-image: url(../content/web/foods/#:data.ProductID#.jpg);'></div><div class='product-name'>#: ProductName #</div>",
                    width: 300
                }],
            });
        });

        function onDataBound(e) {
            var grid = this;
            grid.table.find("tr").each(function () {
                var dataItem = grid.dataItem(this);
                var themeColor = dataItem.Discontinued ? 'success' : 'error';
                var text = dataItem.Discontinued ? 'available' : 'not available';

                $(this).find(".badgeTemplate").kendoBadge({
                    themeColor: themeColor,
                    text: text,
                });

                $(this).find(".rating").kendoRating({
                    min: 1,
                    max: 5,
                    label: false,
                    selection: "continuous"
                });

                $(this).find(".sparkline-chart").kendoSparkline({
                    legend: {
                        visible: false
                    },
                    data: [dataItem.TargetSales],
                    type: "bar",
                    chartArea: {
                        margin: 0,
                        width: 180,
                        background: "transparent"
                    },
                    seriesDefaults: {
                        labels: {
                            visible: true,
                            format: '{0}%',
                            background: 'none'
                        }
                    },
                    categoryAxis: {
                        majorGridLines: {
                            visible: false
                        },
                        majorTicks: {
                            visible: false
                        }
                    },
                    valueAxis: {
                        type: "numeric",
                        min: 0,
                        max: 130,
                        visible: false,
                        labels: {
                            visible: false
                        },
                        minorTicks: { visible: false },
                        majorGridLines: { visible: false }
                    },
                    tooltip: {
                        visible: false
                    }
                });

                kendo.bind($(this), dataItem);
            });
        }

        function returnFalse() {
            return false;
        }

       
    </script>

    <style type="text/css">
        .customer-photo {
            display: inline-block;
            width: 32px;
            height: 32px;
            border-radius: 50%;
            background-size: 32px 35px;
            background-position: center center;
            vertical-align: middle;
            line-height: 32px;
            box-shadow: inset 0 0 1px #999, inset 0 0 10px rgba(0,0,0,.2);
            margin-left: 5px;
        }

        .customer-name {
            display: inline-block;
            vertical-align: middle;
            line-height: 32px;
            padding-left: 3px;
        }

        .k-grid tr .checkbox-align {
            text-align: center;
            vertical-align: middle;
        }

        .product-photo {
            display: inline-block;
            width: 32px;
            height: 32px;
            border-radius: 50%;
            background-size: 32px 35px;
            background-position: center center;
            vertical-align: middle;
            line-height: 32px;
            box-shadow: inset 0 0 1px #999, inset 0 0 10px rgba(0,0,0,.2);
            margin-right: 5px;
        }

        .product-name {
            display: inline-block;
            vertical-align: middle;
            line-height: 32px;
            padding-left: 3px;
        }

        .k-rating-container .k-rating-item {
            padding: 4px 0;
        }

        .k-rating-container .k-rating-item .k-icon {
            font-size: 16px;
        }

        .dropdown-country-wrap {
            display: flex;
            flex-wrap: nowrap;
            align-items: center;
            white-space: nowrap;
        }

        .dropdown-country-wrap img {
            margin-right: 10px;
        }

        #grid .k-grid-edit-row > td > .k-rating {
            margin-left: 0;
            width: 100%;
        }
    </style>
</div>



</body>
</html>

Views/Home/Index.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <link href="~/css/default-main.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <script src="~/js/kendo.all.min.js"></script>
    <script src="~/js/kendo-ui-license.js"></script>
</head>

<body>
    <form id="myForm" action="your-submit-url" method="post">
        @* THE TOP LEVEL INPUT FIELD *@
        <div class="headers ">
            @* //HEADER SECTION OF THE FORM *@
            <div class="k-d-flex k-justify-content-center" style="padding-top: 54px;">
                @* First line of Input *@
                <div class="container ">

                    <div class="row">
                        <div class="k-w-300">
                            <br>
                            <label for="mantralaya"> मन्त्रालय / विभाग / कार्यालय:</label>
                            <input id="mantralaya" />
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="k-w-300">
                        <br>

                        <label for="karlaya"> कार्यालय कोड नं:</label>
                        <input id="karlaya" />
                    </div>
                </div>
            </div>
            @* Second Line of Input *@

            <div class="Container  mt-5">
                <div class="row">
                    <div class="col-sm">
                        <div>
                            <label>आर्थिक वर्ष :</label>
                            <input id="Arthik_barsa" />
                        </div>
                    </div>
                    <div class="col-sm">
                        <div>
                            <label>खर्च निकासा फाराम नं:</label>
                            <input id="Kharcha_Nikasa_No" />
                        </div>
                    </div>
                    <div class="col-sm">
                        <div>
                            <label>खर्च निकासा गरिएका माग फाराम नं.:</label>
                            <input id="Kharcha_form_number" />

                            @* <form id="exampleform"></form> *@

                        </div>
                    </div>
                    <div class="col-sm">
                        <div>
                            <label>मितिः</label>
                            <input id="datetimepicker" />
                        </div>
                    </div>
                </div>
            </div>
        </div>

        @* THE SUB FORM *@
        <div class="container outer">
            <div class="row">
                <div class="col-2">
                    <label for="sn">Serial No.</label>
                    <input name="sn" class="sn">
                </div>
                <div class="col-2">

                </div>
            </div>
        </div>
        <button type="button" id="add_button">Add</button>
        <button type="button" id="submit_button">Submit</button>
    </form>

    <script>

        var mantralaya = "";
        $(document).ready(function () {
            // Initial Kendo UI setup for existing elements
        @* $(".sn").kendoNumericTextBox({}); *@


                $("#add_button").click(function () {
                    console.log("clicked");
                    var clone = $(`
                <div class="col-1" id="inner">
                <label for="sn">Serial No.</label>
                <input id="" name="sn" class="sn">
                </div>`);
                    clone.appendTo(".outer");

                    // Initialize Kendo UI for the newly added element
                    clone.find(".sn").kendoNumericTextBox();
                });

            $("#submit_button").click(function () {
        @* for(var i=0; i < ar.length; i++)
                    {
                    console.log(ar[i].value);
                    }*@
                    console.log("the value of dropdown is", numberBlock);

            });





            //KENDO UI FOR THE HEADER SECTIONS
            function onSelect(e) {
                if (e.dataItem) {
                    var dataItem = e.dataItem;
                    //Console.log("event :: select (" + dataItem.text + " : " + dataItem.value + ")");

                    console.log(dataItem);
                } else {
                    //Console.log("event :: select");
                    console.log(select + "not value");
                }
            };
            $("#mantralaya").kendoDropDownList({
                dataSource: {
                    data: ["Kathmandu", "Lalitpur", "Bhaktapur", "Kavre", "Toursim Board", "Fewa Lake House"]
                },
                select: onSelect

            });
            $("#karlaya").kendoDropDownList({
                dataSource: {
                    transport: {
                        read: {
                            dataType: "json",
                            url: "http://localhost:5268/Home/KarlayaCode",
                        }
                    }
                }

            });
            function onChange() {
                console.log("Change :: " + this.value() + " why this one?");
                numberBlock = this.value();
            }

            function onSpin() {
                console.log("Spin :: " + this.value());
                numberBlock = this.value();

            }

            $(".sn").kendoNumericTextBox({
                change: onChange,
                spin: onSpin
            });
            $("#grid").kendoGrid({
                dataSource: {
                    type: "odata",
                    transport: {
                        read: "https://demos.telerik.com/kendo-ui/service/Northwind.svc/Orders"
                    },
                    schema: {
                        model: {
                            fields: {
                                myArray: { type: "number" }
                            }
                        }
                    },
                    pageSize: 20,
                    serverPaging: true,
                    serverFiltering: true,
                    serverSorting: true
                },
                height: 550,
                columns: [{
                    field: "OrderID",
                    filterable: false
                },
                    "Freight",
                {
                    field: "OrderDate",
                    title: "Order Date",
                    format: "{0:MM/dd/yyyy}"
                }, {
                    field: "ShipName",
                    title: "Ship Name"
                }, {
                    field: "ShipCity",
                    title: "Ship City"
                }
                ]
            });
            $("#Arthik_barsa").kendoDropDownList({
                dataSource: {
                    data: [2024, 2023, 2022, 2021, 2020, 2019, 2018]
                }, select: onSelect
            });
            $("#Kharcha_Nikasa_No").kendoNumericTextBox();
            $("#Kharcha_form_number").kendoNumericTextBox();
            $("#datetimepicker").kendoDatePicker({
                dateInput: true,
                startTime: new Date(2023, 1, 3, 8, 30, 0),
                endTime: new Date(2024, 2, 3, 17,00, 0)
            });
        });
        //KENDO UI FOR THE SUB FORM 


    </script>

</body>

</html>

Views/Home/KendoDropDown.cshtml
<!DOCTYPE html>
<html>
<head>
    <link href="~/css/default-main.css" rel="stylesheet" />
    <script src="https://code.jquery.com/jquery-3.7.0.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <script src="~/js/kendo.all.min.js"></script>
    <script src="~/js/kendo-ui-license.js"></script>
</head>


@*  
<body>
<input class="products" style="width: 100%;"/>
<script>
    $(document).ready(function(){
            $(".products").kendoDropDownList({
                label:{
                    content: "Products",
                    floating: true
                },
                autoBind: false,
                dataTextField: "ProductName",
                dataValueField: "ProductID",
                filter: "contains",
                dataSource:{
                    transport:{
                        read:{
                            dataType:"jsonp",
                            url:"https://demos.telerik.com/kendo-ui/service/Products",
                        }
                    }
                }

    });
    });
</script>
</body>  *@

@* 
<body>
    

		<input class="products" style="width: 90px;" />
	

<script>
    $(document).ready(function() {
        $(".products").kendoDropDownList({
            label: { 
                content: "Product",
                floating: true
            },
            autoBind:false,
            dataTextField: "ProductName",
            dataValueField: "ProductID",
            filter:"contains",
            dataSource: {
                transport: {
                    read: {
                        dataType: "jsonp",
                        url: "https://demos.telerik.com/kendo-ui/service/Products",
                    }
                }
            }
        });
    });
</script>


</body>
</html> *@

<body>
    <input id="products" style="width:90px;"/>
    <script>
        $(document).ready(function(){
            var data=[
            {ProductName:"Beer",ProductID:"1"},
            {ProductName:"Ramin", ProductID:"2"},
            {ProductName:"WaiWai",ProductID:"3"}
            ];
            $("#products").kendoDropDownList({
                dataTextField:"ProductName",
                dataValueField:"ProductID",
                dataSource:data
            });
              var widget = $("#products").getKendoDropDownList();
             var dataSource = widget.dataSource;
              @* if (confirm("Are you sure?")) {
                    dataSource.add({
                    ProductID: 0,
                    ProductName: value
                });
            dataSource.one("sync", function() {
            widget.select(dataSource.view().length - 1);
              });

              dataSource.sync(); *@
        });
    </script>
</body>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - KendoUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    
    

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">KendoUI</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="TestIndex">Demo</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Form" asp-action="Index">Form</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - KendoUI - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    
    
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>